name: Build and Deploy Sphinx Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' 
      - name: OS Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          sudo apt install software-properties-common=0.99.9.12 build-essential=12.8ubuntu1.1 python3.8-venv libhwloc-dev graphviz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m venv .docs-env
          pip install -r requirements.txt
          source .docs-env/bin/activate
      - name: Convert Installation.md to .rst in ttnn and tt-metallium docs
        run: |
          pandoc --from=markdown --to=rst --output=ttnn/ttnn/installing.rst ttnn/ttnn/installing.md
          pandoc --from=markdown --to=rst --output=tt-metalium/installing.rst tt-metalium/installing.md
      - name: Build documentation
        run: |
          python build_docs.py
      - name: Make root index.html
        run: |
          touch output/index.html
          echo -n "docs.tenstorrent.com" > output/CNAME
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
          force_orphan: true