name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: OS Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc
          sudo apt install software-properties-common=0.99.9.12 build-essential=12.8ubuntu1.1 python3.8-venv=3.8.10-0ubuntu1~20.04.10 libgoogle-glog-dev=0.4.0-1build1 libyaml-cpp-dev=0.6.2-4ubuntu1 libboost-all-dev=1.71.0.0ubuntu2 libsndfile1=1.0.28-7ubuntu0.2 libhwloc-dev graphviz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          wget https://github.com/tenstorrent/tt-metal/releases/download/v0.49.0/metal_libs-0.49.0+wormhole.b0-cp38-cp38-linux_x86_64.whl
          pip install --extra-index-url https://download.pytorch.org/whl/cpu metal_libs-0.49.0+wormhole.b0-cp38-cp38-linux_x86_64.whl 
      - name: Build documentation
        run: |
          python build_docs.py
      - name: Make root index.html
        run: |
          touch output/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/
          force_orphan: true